[tool.poetry]
name = "polycrate"
version = "0.34.0"
description = "A client library for accessing Polycrate API"
authors = ["Ayedo Cloud Solutions GmbH"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "polycrate" },
]
include = ["polycrate/py.typed"]

[tool.poetry.dependencies]
python = "^3.11"
httpx = ">=0.23.1,<0.29.0"
attrs = ">=22.2.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["F", "I", "UP"]
