from typing import Literal

ApiV1ActivitiesListKindItem = Literal[
    "alert",
    "announcement",
    "block_action_run",
    "block_action_run_finish",
    "block_action_run_start",
    "check",
    "condition_added",
    "condition_removed",
    "creation",
    "deletion",
    "discovery",
    "downtime",
    "downtime_closed_manually",
    "downtime_ended",
    "downtime_object_added",
    "downtime_object_recovered",
    "downtime_started",
    "downtime_triggered",
    "downtime_updated",
    "generic",
    "incident_created",
    "incident_downtime_linked",
    "incident_downtime_unlinked",
    "incident_status_changed",
    "k8s_app_installation_failed",
    "k8s_app_installed",
    "k8s_app_instance_installed",
    "k8s_app_instance_uninstalled",
    "k8s_app_uninstallation_failed",
    "k8s_app_uninstalled",
    "long_running_task_detected",
    "maintenance_ended",
    "maintenance_scheduled",
    "maintenance_started",
    "note_created",
    "note_reminder",
    "note_reply",
    "note_resolved",
    "notification_send_failed",
    "notification_sent",
    "price_changed",
    "product_cancelled",
    "product_subscribed",
    "reconciliation",
    "repair",
    "replicaset_created",
    "ssh-session",
    "state_changed",
    "statefulset_created",
    "update",
    "workspace-sync",
]

API_V1_ACTIVITIES_LIST_KIND_ITEM_VALUES: set[ApiV1ActivitiesListKindItem] = {
    "alert",
    "announcement",
    "block_action_run",
    "block_action_run_finish",
    "block_action_run_start",
    "check",
    "condition_added",
    "condition_removed",
    "creation",
    "deletion",
    "discovery",
    "downtime",
    "downtime_closed_manually",
    "downtime_ended",
    "downtime_object_added",
    "downtime_object_recovered",
    "downtime_started",
    "downtime_triggered",
    "downtime_updated",
    "generic",
    "incident_created",
    "incident_downtime_linked",
    "incident_downtime_unlinked",
    "incident_status_changed",
    "k8s_app_installation_failed",
    "k8s_app_installed",
    "k8s_app_instance_installed",
    "k8s_app_instance_uninstalled",
    "k8s_app_uninstallation_failed",
    "k8s_app_uninstalled",
    "long_running_task_detected",
    "maintenance_ended",
    "maintenance_scheduled",
    "maintenance_started",
    "note_created",
    "note_reminder",
    "note_reply",
    "note_resolved",
    "notification_send_failed",
    "notification_sent",
    "price_changed",
    "product_cancelled",
    "product_subscribed",
    "reconciliation",
    "repair",
    "replicaset_created",
    "ssh-session",
    "state_changed",
    "statefulset_created",
    "update",
    "workspace-sync",
}


def check_api_v1_activities_list_kind_item(value: str) -> ApiV1ActivitiesListKindItem:
    if value in API_V1_ACTIVITIES_LIST_KIND_ITEM_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {API_V1_ACTIVITIES_LIST_KIND_ITEM_VALUES!r}")
