from typing import Literal

LabelKeysEnum = Literal[
    "polycrate_actionrun_id",
    "polycrate_block_flavor",
    "polycrate_block_id",
    "polycrate_block_implementation",
    "polycrate_block_kind",
    "polycrate_block_name",
    "polycrate_block_type",
    "polycrate_block_version",
    "polycrate_controlled_by",
    "polycrate_criticality",
    "polycrate_discovered",
    "polycrate_endpoint_id",
    "polycrate_endpoint_kind",
    "polycrate_endpoint_name",
    "polycrate_endpoint_remote_address",
    "polycrate_endpoint_remote_port",
    "polycrate_host_id",
    "polycrate_host_name",
    "polycrate_k8sapp_byoa",
    "polycrate_k8sapp_id",
    "polycrate_k8sapp_name",
    "polycrate_k8scluster_id",
    "polycrate_k8scluster_name",
    "polycrate_k8scontrolplane_deployment_checksum",
    "polycrate_k8scontrolplane_id",
    "polycrate_k8scontrolplane_ip_address",
    "polycrate_k8scontrolplane_name",
    "polycrate_k8sworkerpool_id",
    "polycrate_k8sworkerpool_name",
    "polycrate_loadbalancerinstance_deployment_checksum",
    "polycrate_loadbalancerinstance_id",
    "polycrate_loadbalancerinstance_ip_address",
    "polycrate_loadbalancerinstance_name",
    "polycrate_loadbalancerregion_id",
    "polycrate_loadbalancerregion_name",
    "polycrate_log_source",
    "polycrate_managed_by",
    "polycrate_object_id",
    "polycrate_object_name",
    "polycrate_object_type",
    "polycrate_organization_id",
    "polycrate_organization_name",
    "polycrate_organization_slug",
    "polycrate_priority",
    "polycrate_system_name",
    "polycrate_transport",
    "polycrate_worker_block_deployment_checksum",
    "polycrate_worker_block_last_deployed_checksum",
    "polycrate_worker_block_purpose",
    "polycrate_workspace_git_bootstrap",
    "polycrate_workspace_id",
    "polycrate_workspace_name",
]

LABEL_KEYS_ENUM_VALUES: set[LabelKeysEnum] = {
    "polycrate_actionrun_id",
    "polycrate_block_flavor",
    "polycrate_block_id",
    "polycrate_block_implementation",
    "polycrate_block_kind",
    "polycrate_block_name",
    "polycrate_block_type",
    "polycrate_block_version",
    "polycrate_controlled_by",
    "polycrate_criticality",
    "polycrate_discovered",
    "polycrate_endpoint_id",
    "polycrate_endpoint_kind",
    "polycrate_endpoint_name",
    "polycrate_endpoint_remote_address",
    "polycrate_endpoint_remote_port",
    "polycrate_host_id",
    "polycrate_host_name",
    "polycrate_k8sapp_byoa",
    "polycrate_k8sapp_id",
    "polycrate_k8sapp_name",
    "polycrate_k8scluster_id",
    "polycrate_k8scluster_name",
    "polycrate_k8scontrolplane_deployment_checksum",
    "polycrate_k8scontrolplane_id",
    "polycrate_k8scontrolplane_ip_address",
    "polycrate_k8scontrolplane_name",
    "polycrate_k8sworkerpool_id",
    "polycrate_k8sworkerpool_name",
    "polycrate_loadbalancerinstance_deployment_checksum",
    "polycrate_loadbalancerinstance_id",
    "polycrate_loadbalancerinstance_ip_address",
    "polycrate_loadbalancerinstance_name",
    "polycrate_loadbalancerregion_id",
    "polycrate_loadbalancerregion_name",
    "polycrate_log_source",
    "polycrate_managed_by",
    "polycrate_object_id",
    "polycrate_object_name",
    "polycrate_object_type",
    "polycrate_organization_id",
    "polycrate_organization_name",
    "polycrate_organization_slug",
    "polycrate_priority",
    "polycrate_system_name",
    "polycrate_transport",
    "polycrate_worker_block_deployment_checksum",
    "polycrate_worker_block_last_deployed_checksum",
    "polycrate_worker_block_purpose",
    "polycrate_workspace_git_bootstrap",
    "polycrate_workspace_id",
    "polycrate_workspace_name",
}


def check_label_keys_enum(value: str) -> LabelKeysEnum:
    if value in LABEL_KEYS_ENUM_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {LABEL_KEYS_ENUM_VALUES!r}")
